name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"

      - name: Go Tests
        run: go test ./... -cover

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"

      - name: Go Lint
        run: test -z $(go fmt ./...)

      - name: Go staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./...

  security:
    name: Security
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"

      - name: Go Security Check
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest && gosec ./...
